@startuml
' Scope: A single software system.
' Primary elements: Containers within the software system in scope.
' Supporting elements: People and software systems directly connected to the containers.
' Intended audience: Technical people inside and outside of the software development team;
'                    including software architects, developers and operations/support staff.
'Notes: This diagram says nothing about deployment scenarios, clustering, replication, failover, etc. 
!include ./C4-PlantUML/C4_Container.puml

title Container Template

@enduml