@startuml
' Scope: A single software system.
' Primary elements: Containers within the software system in scope.
' Supporting elements: People and software systems directly connected to the containers.
' Intended audience: Technical people inside and outside of the software development team;
'                    including software architects, developers and operations/support staff.
'Notes: This diagram says nothing about deployment scenarios, clustering, replication, failover, etc. 

!includeurl https://raw.githubusercontent.com/sbidy/Threat.UML/git_access/C4-PlantUML/C4_Container.puml

LAYOUT_WITH_LEGEND()
'LAYOUT_AS_DRAFT()

Set_Title("Container Template")
Autor("Autors name")


@enduml
