@startuml
' Scope: A single software system.
' Primary elements: The software system in scope.
' Supporting elements: People and software systems directly connected to the software system in scope.
' Intended audience: Everybody, both technical and non-technical people, inside and outside of the software development team.
' 
LAYOUT_WITH_LEGEND()
'LAYOUT_AS_DRAFT()

Set_Titel("Context Template")
Autor("Autors name")

@enduml
